ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  extensions:
    health_check: {}
    memory_ballast:
      size_in_percentage: 20
agentCollector:
  enabled: false
  # configOverride:
  #   exporters: 
  #     otlp:
  #       endpoint: "otel-collector-opentelemetry-collector.default:4317"
  #       tls:
  #         insecure: true
  #       sending_queue:
  #         num_consumers: 4
  #         queue_size: 100
  #       retry_on_failure:
  #         enabled: true
  #   processors:
  #     batch:
  #     resource:
  #       attributes:
  #       - key: k8s.cluster.region
  #         value: "region-name"
  #         action: insert
  #       - key: k8s.cluster.name
  #         value: "cluster-name"
  #         action: insert
  #       - key: k8s.cluster.env
  #         value: "environment-name"
  #         action: insert
  #     memory_limiter:
  #       check_interval: 1s
  #       limit_percentage: 50
  #       spike_limit_percentage: 30
  #   service:
  #     pipelines:
  #       traces/1:
  #         receivers: [otlp]
  #         processors: [memory_limiter, batch, resource]
  #         exporters: [otlp]
standaloneCollector:
  enabled: true
  replicaCount: 1
  configOverride:
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
    exporters:
      logging:
        loglevel: info
      otlp/data-prepper:
        endpoint: data-prepper-headless:21890
        tls:
          insecure: true
    service:
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp/data-prepper]