apiVersion: v2
name: elastic-kibana
version: 0.1.1
appVersion: 7.16.2

dependencies:
  - name: elasticsearch 
    version: 7.16.2
    repository: https://helm.elastic.co
    alias: master

  - name: elasticsearch 
    version: 7.16.2
    repository: https://helm.elastic.co
    alias: data

  - name: elasticsearch 
    version: 7.16.2
    repository: https://helm.elastic.co
    alias: client

  - name: kibana 
    version: 7.12.1
    repository: https://helm.elastic.co

  - name: prometheus-elasticsearch-exporter
    version: 4.11.0
    repository:	https://prometheus-community.github.io/helm-charts