apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- if .Values.service.ports }}
  {{- range $port := .Values.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.containerPort }}
    targetPort: {{ $port.containerPort }}
    protocol: {{ $port.protocol }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
