apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jenkins-agent.fullname" . }}
  labels:
    {{- include "jenkins-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jenkins-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jenkins-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: {{ toYaml .Values.env | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: jenkins-agent-data
              mountPath: /home/jenkins/agent
      {{- if not .Values.persistence.enabled }}
      volumes:
      - name: jenkins-agent-data
        emptyDir: {}
      {{- else if .Values.persistence.existingClaim }}
      volumes:
      - name: jenkins-agent-data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim }}
      {{- else }}
      volumes:
      - name: jenkins-agent-data
        persistentVolumeClaim:
          claimName: {{ include "jenkins-agent.fullname" . }}-claim
      {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
