apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://admin-cluster-client.default.svc.cluster.local:9200
        username: elastic
        password: <password>
        tls:
          skip-host-verify: true