apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert
spec:
  dnsNames:
  - '*.myapp.io'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: my-cert
  secretTemplate:
    annotations:
      kubed.appscode.com/sync-contexts: destination-cluster
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""